# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases 
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install

script:
  - phpunit --configuration phpunit.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "eric.poe@gmail.com"
